name: testing_cz2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  http: ^0.13.5
  flutter_switch: ^0.3.2
  
  flutter:
    sdk: flutter
  geocoding: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/fonts/Montserrat-Light.ttf
        - asset: lib/fonts/Montserrat-Regular.ttf
        - asset: lib/fonts/Montserrat-Bold.ttf